// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../src/components/header';
import Footer from "../src/components/footer";
import AuthProvider from '../src/providers/AuthProvider'; // Import your AuthProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
